export enum Errors {
    PROGRAMME_ERROR = "PROGRAMME_ERROR",
    NOT_EQUAL       = "NOT_EQUAL",
    NOT_MATCHED     = "NOT_MATCHED",
    NOT_EXIST       = "NOT_EXIST",
    NOT_ALLOW_EMPTY = "NOT_ALLOW_EMPTY",
    DUPLICATED      = "DUPLICATED",
    IMPOSSIBLE      = "IMPOSSIBLE",
    INVALID_INPUT   = "INVALID_INPUT",
    NOT_IMPLEMENTED = "NOT_IMPLEMENTED",
}